const posts = [
  {
    id: 1,
    username: 'nowboarder1',
    location: ["Sydney", "Australia"],
    name: "Yes Hel Yes",
    image: "https://pacificboarder.com/cdn/shop/products/210000040669YesHelYesSnowboard2022_1080x.jpg?v=1633108580",
    category: ["snowboard", "used"],
    price: "450.00",
    description:
      "2022 model 149cm snowboard, used for 2 seasons, has a few marks on top sheet, rides well but selling as too long for me, $699.00 brand new usually",
  },
  {
    id: 2,
    username: 'nowboarder1',
    location: ['Sydney', 'Australia'],
    name: "Capita Space Metal Fantasy",
    image: "https://www.melbournesnowboard.com.au/cdn/shop/products/0070_PRK05-SMF-145_png_1200x.jpg?v=1620876037",
    category: ["snowboard", "used"],
    price: "300.00",
    description:
      "142cm snowboard, used for 1 season, good for buttering but selling as doesn't ride it that much",
  },
  {
    id: 3,
    username: 'nowboarder2',
    location: ['Melbourne', 'Australia'],
    name: "Bataleon Distortia",
    image: "https://www.melbournesnowboard.com.au/cdn/shop/products/Distortia_645fa165-4a45-4400-86b1-f9d3e00e0d0f_1000x.jpg?v=1581387679",
    category: ["snowboard", "new"],
    price: "500.00",
    description: "139 cm snowboard, brand new, selling as too short for me",
  },
  {
    id: 4,
    username: "nowboarder2",
    location: ['Melbourne', 'Australia'],
    name: "Burton Gore-Tex Gloves Women's Black",
    image: "https://www.auski.com.au/cdn/shop/products/burton-women_s-burton-gore-tex-gloves-true-black-1_5000x.jpg?v=1663222245",
    category: ["gloves", "used"],
    price: "90.00",
    description: "used gloves, very warm",
  },
  {
    id: 5,
    username: 'nowboarder3',
    location: ['Sydney', 'Australia'],
    name: "Anon Raider 3",
    image: "https://www.melbournesnowboard.com.au/cdn/shop/products/0000_21429100001_1_3cd58114-2ad3-48f8-af92-747fa96e08db_800x.jpg?v=1637886739",
    category: ["helmet", "used"],
    price: "80.00",
    description: "Size M, few scratches on it but no other damage",
  },
  {
    id: 6,
    username: 'nowboarder4',
    location: ['Adelaide', 'Australia'],
    name: "Burton Lexa Black Bindings",
    image: "https://www.whiteroomsnow.com.au/cdn/shop/products/10545107002_1_1080x.jpg?v=1606278929",
    category: ["bindings", "used"],
    price: "250.00",
    description:
      "size M, few scratches from wear and tear but no other damage, fully functioning",
  },
  {
    id: 7,
    username: 'nowboarder3',
    location: ['Sydney', 'Australia'],
    name: "Burton Felix Boots Size 7",
    image: "https://proski.com.au/wp-content/uploads/2020/12/burton-felix-boa-black-gold.jpg",
    category: ["boots", "used"],
    price: "400.00",
    description:
      "size 7, used for 2 seasons, can be heat molded again to suit your feet or get new insoles",
  },
  {
    id: 8,
    username: "nowboarder6",
    location: ['Melbourne', 'Australia'],
    name: "Anon M4S Cylindrical Low Bridge Jade",
    image: "https://snowskierswarehouse.com.au/cdn/shop/products/23574100300_4_1200x.jpg?v=1666339144",
    category: ["goggle", "used"],
    price: "300.00",
    description:
      "like new, used a couple of times, no scratches or any marks, comes with extra lens and magnetic face mask",
  },
  {
    id: 9,
    username: 'nowboarder5',
    location: ['Sydney', 'Australia'],
    name: "Dakine Tour Bag",
    image: "https://www.melbournesnowboard.com.au/cdn/shop/products/TourBegonia.jpg?v=1678849016",
    category: ["accessory", "new"],
    price: "120.00",
    description: "157cm, brand new snowboard bag",
  },
  {
    id: 10,
    username: 'nowboarder5',
    location: ['Sydney', 'Australia'],
    name: "Airblaster Lady Trenchover Daisy Daiquiri ",
    image: "https://time2ride.com.au/cdn/shop/products/LADY_TRENCHOVER_LAV_DAISY_DAIQUIRI_2122_480x480.jpg?v=1648250836",
    category: ["clothing", "new"],
    price: "500.00",
    description: "M sized, warm and cute",
  },
{
  id: 11,
  username: "nowboarder5",
  location: ['Sydney', 'Australia'],
  name: "White Snowboard pants ",
  image: "https://www.melbournesnowboard.com.au/cdn/shop/products/roxy-backyard-pant-white_1200x.jpg?v=1678848078",
  category: ["clothing", "used"],
  price: "100.00",
  description: "M sized, warm and cute, works well with posted Trenchover",
},
];